export const AppConstants = {
  USER_EMAIL: import.meta.env.USER_EMAIL ?? "resumeway2024@bluebenz.com",
  USER_PASSWORD: import.meta.env.USER_PASSWORD ?? "resumeway2024",
  JD_DATA: [
    {
      title: "Software Engineer",
      openPositions: 5,
      experience: "2-5 years",
      profileLocation: "New York, NY",
      updatedDate: "2024-05-14",
      status: "Active",
    },
    {
      title: "Web Developer",
      openPositions: 3,
      experience: "1-3 years",
      profileLocation: "San Francisco, CA",
      updatedDate: "2024-05-13",
      status: "Active",
    },
    {
      title: "Frontend Developer",
      openPositions: 2,
      experience: "3-5 years",
      profileLocation: "London, UK",
      updatedDate: "2024-05-12",
      status: "Inactive",
    },
    {
      title: "Full Stack Developer",
      openPositions: 4,
      experience: "2-4 years",
      profileLocation: "Berlin, Germany",
      updatedDate: "2024-05-14",
      status: "Active",
    },
    {
      title: "iOS Developer",
      openPositions: 1,
      experience: "5+ years",
      profileLocation: "Tokyo, Japan",
      updatedDate: "2024-05-10",
      status: "Active",
    },
    {
      title: "Backend Developer",
      openPositions: 2,
      experience: "3-6 years",
      profileLocation: "Toronto, Canada",
      updatedDate: "2024-05-11",
      status: "Active",
    },
    {
      title: "UI/UX Designer",
      openPositions: 3,
      experience: "2-4 years",
      profileLocation: "Paris, France",
      updatedDate: "2024-05-12",
      status: "Inactive",
    },
    {
      title: "Data Scientist",
      openPositions: 2,
      experience: "4-7 years",
      profileLocation: "Sydney, Australia",
      updatedDate: "2024-05-14",
      status: "Active",
    },
    {
      title: "Machine Learning Engineer",
      openPositions: 1,
      experience: "3-5 years",
      profileLocation: "Seoul, South Korea",
      updatedDate: "2024-05-13",
      status: "Active",
    },
    {
      title: "DevOps Engineer",
      openPositions: 2,
      experience: "3-6 years",
      profileLocation: "Amsterdam, Netherlands",
      updatedDate: "2024-05-14",
      status: "Inactive",
    },
  ],
  APPLICATIONS: [
    {
      name: "John Doe",
      skill: "Python",
      experience: "1-2 years",
      location: "New York, San Francisco",
      score: 87,
    },
    {
      name: "Jane Smith",
      skill: "JavaScript",
      experience: "3-4 years",
      location: "Seattle, Boston",
      score: 32,
    },
    {
      name: "Michael Johnson",
      skill: "Java",
      experience: "5-6 years",
      location: "Chicago, Los Angeles",
      score: 78,
    },
    {
      name: "Emily Brown",
      skill: "C++",
      experience: "7-8 years",
      location: "San Francisco, Dallas",
      score: 50,
    },
    {
      name: "David Wilson",
      skill: "Ruby",
      experience: "1-2 years",
      location: "Boston, Atlanta",
      score: 75,
    },
    {
      name: "Sarah Taylor",
      skill: "C#",
      experience: "3-4 years",
      location: "Los Angeles, Seattle",
      score: 88,
    },
    {
      name: "Chris Martinez",
      skill: "PHP",
      experience: "5-6 years",
      location: "Chicago, New York",
      score: 20,
    },
    {
      name: "Amanda Lee",
      skill: "Swift",
      experience: "7-8 years",
      location: "San Francisco, Boston",
      score: 90,
    },
    {
      name: "Daniel Clark",
      skill: "SQL",
      experience: "1-2 years",
      location: "Seattle, Chicago",
      score: 63,
    },
    {
      name: "Olivia Garcia",
      skill: "R",
      experience: "3-4 years",
      location: "Boston, Dallas",
      score: 50,
    },
  ],
};
